# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowList(object):
    def setupUi(self, MainWindowList):
        MainWindowList.setObjectName("MainWindowList")
        MainWindowList.resize(300, 140)
        MainWindowList.setMaximumSize(QtCore.QSize(300, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindowList)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.keys_label_18 = QtWidgets.QLabel(self.centralwidget)
        self.keys_label_18.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_18.setFont(font)
        self.keys_label_18.setStyleSheet("\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_18.setObjectName("keys_label_18")
        self.horizontalLayout_2.addWidget(self.keys_label_18)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lineConfig = QtWidgets.QLineEdit(self.centralwidget)
        self.lineConfig.setMinimumSize(QtCore.QSize(150, 30))
        self.lineConfig.setObjectName("lineConfig")
        self.verticalLayout.addWidget(self.lineConfig)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_config_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_config_button.setMinimumSize(QtCore.QSize(115, 35))
        self.save_config_button.setSizeIncrement(QtCore.QSize(0, 0))
        self.save_config_button.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.save_config_button.setObjectName("save_config_button")
        self.horizontalLayout.addWidget(self.save_config_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindowList.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowList)
        QtCore.QMetaObject.connectSlotsByName(MainWindowList)

    def retranslateUi(self, MainWindowList):
        _translate = QtCore.QCoreApplication.translate
        MainWindowList.setWindowTitle(_translate("MainWindowList", "Сохранение конфигурации"))
        self.keys_label_18.setText(_translate("MainWindowList", "Введите название конфигурации"))
        self.save_config_button.setText(_translate("MainWindowList", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowList = QtWidgets.QMainWindow()
    ui = Ui_MainWindowList()
    ui.setupUi(MainWindowList)
    MainWindowList.show()
    sys.exit(app.exec_())
