# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1589, 985)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.filter_groupbox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.filter_groupbox_3.setMinimumSize(QtCore.QSize(504, 297))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filter_groupbox_3.setFont(font)
        self.filter_groupbox_3.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0px;\n"
"    background-color: #658FB7\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: 0px;\n"
"  padding-left: 8px;\n"
"}")
        self.filter_groupbox_3.setObjectName("filter_groupbox_3")
        self.comboBox_keys_2 = QtWidgets.QComboBox(self.filter_groupbox_3)
        self.comboBox_keys_2.setGeometry(QtCore.QRect(30, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_keys_2.setFont(font)
        self.comboBox_keys_2.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_keys_2.setObjectName("comboBox_keys_2")
        self.comboBox_keys_2.addItem("")
        self.checkBox_filter_2 = QtWidgets.QCheckBox(self.filter_groupbox_3)
        self.checkBox_filter_2.setGeometry(QtCore.QRect(20, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_filter_2.setFont(font)
        self.checkBox_filter_2.setStyleSheet("background-color: #658FB7;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.checkBox_filter_2.setObjectName("checkBox_filter_2")
        self.list_selected_unique_keys_2 = QtWidgets.QListWidget(self.filter_groupbox_3)
        self.list_selected_unique_keys_2.setGeometry(QtCore.QRect(280, 90, 211, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_selected_unique_keys_2.setFont(font)
        self.list_selected_unique_keys_2.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_selected_unique_keys_2.setObjectName("list_selected_unique_keys_2")
        self.pushButton_delete_unique_keys_2 = QtWidgets.QPushButton(self.filter_groupbox_3)
        self.pushButton_delete_unique_keys_2.setGeometry(QtCore.QRect(240, 140, 31, 31))
        self.pushButton_delete_unique_keys_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_delete_unique_keys_2.setObjectName("pushButton_delete_unique_keys_2")
        self.pushButton_add_unique_keys_2 = QtWidgets.QPushButton(self.filter_groupbox_3)
        self.pushButton_add_unique_keys_2.setGeometry(QtCore.QRect(240, 190, 31, 31))
        self.pushButton_add_unique_keys_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add_unique_keys_2.setObjectName("pushButton_add_unique_keys_2")
        self.list_unique_keys_2 = QtWidgets.QListWidget(self.filter_groupbox_3)
        self.list_unique_keys_2.setGeometry(QtCore.QRect(20, 90, 211, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_unique_keys_2.setFont(font)
        self.list_unique_keys_2.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}")
        self.list_unique_keys_2.setObjectName("list_unique_keys_2")
        self.keys_label_14 = QtWidgets.QLabel(self.filter_groupbox_3)
        self.keys_label_14.setGeometry(QtCore.QRect(20, 40, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_14.setFont(font)
        self.keys_label_14.setStyleSheet("background-color: #658FB7;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_14.setObjectName("keys_label_14")
        self.pushButton_filter_clear_keys_2 = QtWidgets.QPushButton(self.filter_groupbox_3)
        self.pushButton_filter_clear_keys_2.setGeometry(QtCore.QRect(390, 270, 81, 20))
        self.pushButton_filter_clear_keys_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#CC0000;\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_filter_clear_keys_2.setObjectName("pushButton_filter_clear_keys_2")
        self.lineEdit_filter_2 = QtWidgets.QLineEdit(self.filter_groupbox_3)
        self.lineEdit_filter_2.setGeometry(QtCore.QRect(290, 40, 191, 21))
        self.lineEdit_filter_2.setObjectName("lineEdit_filter_2")
        self.pushButton_filter_download_keys_2 = QtWidgets.QPushButton(self.filter_groupbox_3)
        self.pushButton_filter_download_keys_2.setGeometry(QtCore.QRect(290, 70, 103, 21))
        self.pushButton_filter_download_keys_2.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_filter_download_keys_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_filter_download_keys_2.setObjectName("pushButton_filter_download_keys_2")
        self.keys_label_21 = QtWidgets.QLabel(self.filter_groupbox_3)
        self.keys_label_21.setGeometry(QtCore.QRect(290, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_21.setFont(font)
        self.keys_label_21.setStyleSheet("background-color: #658FB7;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_21.setObjectName("keys_label_21")
        self.gridLayout_2.addWidget(self.filter_groupbox_3, 5, 2, 1, 1)
        self.groupBox_secondary_file = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_secondary_file.setMinimumSize(QtCore.QSize(773, 517))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_secondary_file.setFont(font)
        self.groupBox_secondary_file.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0px;\n"
"    background-color: #85A8CA\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: 0px;\n"
"  padding-left: 8px;\n"
"}")
        self.groupBox_secondary_file.setObjectName("groupBox_secondary_file")
        self.button_open_file_2 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.button_open_file_2.setGeometry(QtCore.QRect(10, 20, 124, 23))
        self.button_open_file_2.setMinimumSize(QtCore.QSize(120, 0))
        self.button_open_file_2.setAutoFillBackground(False)
        self.button_open_file_2.setStyleSheet("\n"
"QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }\n"
"")
        self.button_open_file_2.setCheckable(False)
        self.button_open_file_2.setChecked(False)
        self.button_open_file_2.setAutoRepeatDelay(300)
        self.button_open_file_2.setObjectName("button_open_file_2")
        self.keys_label_3 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_3.setGeometry(QtCore.QRect(280, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_3.setFont(font)
        self.keys_label_3.setStyleSheet("background-color: #85A8CA;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"")
        self.keys_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_3.setObjectName("keys_label_3")
        self.keys_label_5 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_5.setGeometry(QtCore.QRect(10, 140, 201, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_5.setFont(font)
        self.keys_label_5.setStyleSheet("background-color: #85A8CA;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"")
        self.keys_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_5.setObjectName("keys_label_5")
        self.list_selected_keys_2 = QtWidgets.QListWidget(self.groupBox_secondary_file)
        self.list_selected_keys_2.setGeometry(QtCore.QRect(20, 160, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_selected_keys_2.setFont(font)
        self.list_selected_keys_2.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_selected_keys_2.setObjectName("list_selected_keys_2")
        self.list_keys_2 = QtWidgets.QListWidget(self.groupBox_secondary_file)
        self.list_keys_2.setGeometry(QtCore.QRect(280, 160, 211, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_keys_2.setFont(font)
        self.list_keys_2.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}")
        self.list_keys_2.setObjectName("list_keys_2")
        self.pushButton_delete_2 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_delete_2.setGeometry(QtCore.QRect(240, 240, 31, 31))
        self.pushButton_delete_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_delete_2.setObjectName("pushButton_delete_2")
        self.pushButton_add_2 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_add_2.setGeometry(QtCore.QRect(240, 190, 31, 31))
        self.pushButton_add_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add_2.setObjectName("pushButton_add_2")
        self.pushButton_down_2 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_down_2.setGeometry(QtCore.QRect(130, 290, 31, 31))
        self.pushButton_down_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_down_2.setObjectName("pushButton_down_2")
        self.pushButton_up_2 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_up_2.setGeometry(QtCore.QRect(80, 290, 31, 31))
        self.pushButton_up_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_up_2.setObjectName("pushButton_up_2")
        self.comboBox_list_2 = QtWidgets.QComboBox(self.groupBox_secondary_file)
        self.comboBox_list_2.setGeometry(QtCore.QRect(340, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_list_2.setFont(font)
        self.comboBox_list_2.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_list_2.setObjectName("comboBox_list_2")
        self.comboBox_list_2.addItem("")
        self.list_selected_keys_3 = QtWidgets.QListWidget(self.groupBox_secondary_file)
        self.list_selected_keys_3.setGeometry(QtCore.QRect(540, 350, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_selected_keys_3.setFont(font)
        self.list_selected_keys_3.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_selected_keys_3.setObjectName("list_selected_keys_3")
        self.pushButton_delete_3 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_delete_3.setGeometry(QtCore.QRect(500, 370, 31, 31))
        self.pushButton_delete_3.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_delete_3.setObjectName("pushButton_delete_3")
        self.pushButton_add_3 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_add_3.setGeometry(QtCore.QRect(500, 420, 31, 31))
        self.pushButton_add_3.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add_3.setObjectName("pushButton_add_3")
        self.keys_label_7 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_7.setGeometry(QtCore.QRect(550, 330, 181, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_7.setFont(font)
        self.keys_label_7.setStyleSheet("background-color: #85A8CA;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"")
        self.keys_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_7.setObjectName("keys_label_7")
        self.pushButton_up_3 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_up_3.setGeometry(QtCore.QRect(600, 480, 31, 31))
        self.pushButton_up_3.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_up_3.setObjectName("pushButton_up_3")
        self.pushButton_down_3 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_down_3.setGeometry(QtCore.QRect(650, 480, 31, 31))
        self.pushButton_down_3.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_down_3.setObjectName("pushButton_down_3")
        self.keys_label_9 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_9.setGeometry(QtCore.QRect(330, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_9.setFont(font)
        self.keys_label_9.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #85A8CA;")
        self.keys_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_9.setObjectName("keys_label_9")
        self.keys_label_11 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_11.setGeometry(QtCore.QRect(340, 80, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_11.setFont(font)
        self.keys_label_11.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #85A8CA;")
        self.keys_label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_11.setObjectName("keys_label_11")
        self.spinBox_list_2 = QtWidgets.QSpinBox(self.groupBox_secondary_file)
        self.spinBox_list_2.setGeometry(QtCore.QRect(340, 100, 141, 31))
        self.spinBox_list_2.setMinimum(1)
        self.spinBox_list_2.setMaximum(9999)
        self.spinBox_list_2.setProperty("value", 1)
        self.spinBox_list_2.setObjectName("spinBox_list_2")
        self.keys_label_13 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_13.setGeometry(QtCore.QRect(20, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_13.setFont(font)
        self.keys_label_13.setStyleSheet("background-color: #85A8CA;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_13.setObjectName("keys_label_13")
        self.comboBox_head_2 = QtWidgets.QComboBox(self.groupBox_secondary_file)
        self.comboBox_head_2.setGeometry(QtCore.QRect(20, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_head_2.setFont(font)
        self.comboBox_head_2.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_head_2.setObjectName("comboBox_head_2")
        self.comboBox_head_2.addItem("")
        self.comboBox_head_2.addItem("")
        self.button_auto_select_str_2 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.button_auto_select_str_2.setGeometry(QtCore.QRect(290, 100, 41, 31))
        self.button_auto_select_str_2.setAutoFillBackground(False)
        self.button_auto_select_str_2.setStyleSheet("\n"
"QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }\n"
"")
        self.button_auto_select_str_2.setText("")
        self.button_auto_select_str_2.setCheckable(False)
        self.button_auto_select_str_2.setChecked(False)
        self.button_auto_select_str_2.setAutoRepeatDelay(300)
        self.button_auto_select_str_2.setObjectName("button_auto_select_str_2")
        self.keys_label_20 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_20.setGeometry(QtCore.QRect(280, 80, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_20.setFont(font)
        self.keys_label_20.setStyleSheet("background-color: #85A8CA;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_20.setObjectName("keys_label_20")
        self.keys_label_calculations_2 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_calculations_2.setGeometry(QtCore.QRect(20, 330, 201, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_calculations_2.setFont(font)
        self.keys_label_calculations_2.setStyleSheet("background-color: #85A8CA;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"")
        self.keys_label_calculations_2.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_calculations_2.setObjectName("keys_label_calculations_2")
        self.list_selected_keys_5 = QtWidgets.QListWidget(self.groupBox_secondary_file)
        self.list_selected_keys_5.setGeometry(QtCore.QRect(20, 350, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_selected_keys_5.setFont(font)
        self.list_selected_keys_5.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_selected_keys_5.setObjectName("list_selected_keys_5")
        self.pushButton_add_5 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_add_5.setGeometry(QtCore.QRect(240, 370, 31, 31))
        self.pushButton_add_5.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add_5.setObjectName("pushButton_add_5")
        self.pushButton_delete_5 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_delete_5.setGeometry(QtCore.QRect(240, 420, 31, 31))
        self.pushButton_delete_5.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_delete_5.setObjectName("pushButton_delete_5")
        self.pushButton_up_5 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_up_5.setGeometry(QtCore.QRect(80, 480, 31, 31))
        self.pushButton_up_5.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_up_5.setObjectName("pushButton_up_5")
        self.pushButton_down_5 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_down_5.setGeometry(QtCore.QRect(130, 480, 31, 31))
        self.pushButton_down_5.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_down_5.setObjectName("pushButton_down_5")
        self.list_table_selected_2 = QtWidgets.QListWidget(self.groupBox_secondary_file)
        self.list_table_selected_2.setGeometry(QtCore.QRect(540, 160, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_table_selected_2.setFont(font)
        self.list_table_selected_2.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_table_selected_2.setObjectName("list_table_selected_2")
        self.keys_label_17 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_17.setGeometry(QtCore.QRect(550, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_17.setFont(font)
        self.keys_label_17.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #85A8CA;")
        self.keys_label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_17.setObjectName("keys_label_17")
        self.keys_label_22 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.keys_label_22.setGeometry(QtCore.QRect(540, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_22.setFont(font)
        self.keys_label_22.setStyleSheet("background-color: #85A8CA;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_22.setObjectName("keys_label_22")
        self.comboBox_config_2 = QtWidgets.QComboBox(self.groupBox_secondary_file)
        self.comboBox_config_2.setGeometry(QtCore.QRect(540, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_config_2.setFont(font)
        self.comboBox_config_2.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_config_2.setObjectName("comboBox_config_2")
        self.comboBox_config_2.addItem("")
        self.pushButton_add_config_2 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_add_config_2.setGeometry(QtCore.QRect(540, 70, 121, 21))
        self.pushButton_add_config_2.setMinimumSize(QtCore.QSize(101, 0))
        self.pushButton_add_config_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0,150, 20);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add_config_2.setObjectName("pushButton_add_config_2")
        self.pushButton_filter_del_config_2 = QtWidgets.QPushButton(self.groupBox_secondary_file)
        self.pushButton_filter_del_config_2.setGeometry(QtCore.QRect(670, 70, 81, 21))
        self.pushButton_filter_del_config_2.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#CC0000;\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_filter_del_config_2.setObjectName("pushButton_filter_del_config_2")
        self.msg_label_2 = QtWidgets.QLabel(self.groupBox_secondary_file)
        self.msg_label_2.setGeometry(QtCore.QRect(540, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.msg_label_2.setFont(font)
        self.msg_label_2.setStyleSheet("background-color: #85A8CA;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.msg_label_2.setText("")
        self.msg_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_label_2.setObjectName("msg_label_2")
        self.checkBox_group_str_2 = QtWidgets.QCheckBox(self.groupBox_secondary_file)
        self.checkBox_group_str_2.setGeometry(QtCore.QRect(10, 50, 221, 20))
        self.checkBox_group_str_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_group_str_2.setFont(font)
        self.checkBox_group_str_2.setStyleSheet("QCheckBox {\n"
"      background-color: #85A8CA;\n"
"    border: 0px solid gray;\n"
"    border-radius: 0px;    \n"
"}\n"
"\n"
"")
        self.checkBox_group_str_2.setChecked(False)
        self.checkBox_group_str_2.setObjectName("checkBox_group_str_2")
        self.gridLayout_2.addWidget(self.groupBox_secondary_file, 3, 2, 1, 2)
        self.filter_groupbox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.filter_groupbox_2.setMinimumSize(QtCore.QSize(0, 50))
        self.filter_groupbox_2.setMaximumSize(QtCore.QSize(1544, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filter_groupbox_2.setFont(font)
        self.filter_groupbox_2.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0px;\n"
"    background-color: #bbbbbb;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: 0px;\n"
"  padding-left: 8px;\n"
"}")
        self.filter_groupbox_2.setTitle("")
        self.filter_groupbox_2.setObjectName("filter_groupbox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.filter_groupbox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBarMsg = QtWidgets.QLabel(self.filter_groupbox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarMsg.sizePolicy().hasHeightForWidth())
        self.progressBarMsg.setSizePolicy(sizePolicy)
        self.progressBarMsg.setMinimumSize(QtCore.QSize(218, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBarMsg.setFont(font)
        self.progressBarMsg.setStyleSheet("background-color: #bbbbbb;")
        self.progressBarMsg.setObjectName("progressBarMsg")
        self.horizontalLayout.addWidget(self.progressBarMsg)
        self.progressBar = QtWidgets.QProgressBar(self.filter_groupbox_2)
        self.progressBar.setMinimumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("color: rgb(42, 138, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.comboBox_function = QtWidgets.QComboBox(self.filter_groupbox_2)
        self.comboBox_function.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_function.setFont(font)
        self.comboBox_function.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_function.setObjectName("comboBox_function")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_function)
        self.result_button = QtWidgets.QPushButton(self.filter_groupbox_2)
        self.result_button.setMinimumSize(QtCore.QSize(120, 32))
        self.result_button.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.result_button.setObjectName("result_button")
        self.horizontalLayout.addWidget(self.result_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.filter_groupbox_2, 6, 1, 1, 3)
        self.filter_groupbox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.filter_groupbox_4.setMinimumSize(QtCore.QSize(263, 297))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filter_groupbox_4.setFont(font)
        self.filter_groupbox_4.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0px;\n"
"    background-color: #33CCCC;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: 0px;\n"
"  padding-left: 8px;\n"
"}")
        self.filter_groupbox_4.setObjectName("filter_groupbox_4")
        self.checkBox_open = QtWidgets.QCheckBox(self.filter_groupbox_4)
        self.checkBox_open.setGeometry(QtCore.QRect(10, 20, 231, 51))
        self.checkBox_open.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_open.setFont(font)
        self.checkBox_open.setStyleSheet("QCheckBox {\n"
"      background-color: #33CCCC;\n"
"    border: 0px solid gray;\n"
"    border-radius: 0px;    \n"
"}\n"
"\n"
"")
        self.checkBox_open.setChecked(True)
        self.checkBox_open.setObjectName("checkBox_open")
        self.checkBox_color = QtWidgets.QCheckBox(self.filter_groupbox_4)
        self.checkBox_color.setGeometry(QtCore.QRect(10, 70, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_color.setFont(font)
        self.checkBox_color.setStyleSheet("background-color: #33CCCC;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.checkBox_color.setChecked(True)
        self.checkBox_color.setObjectName("checkBox_color")
        self.checkBox_join_keys = QtWidgets.QCheckBox(self.filter_groupbox_4)
        self.checkBox_join_keys.setGeometry(QtCore.QRect(10, 170, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_join_keys.setFont(font)
        self.checkBox_join_keys.setStyleSheet("background-color: #33CCCC;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.checkBox_join_keys.setObjectName("checkBox_join_keys")
        self.keys_label_6 = QtWidgets.QLabel(self.filter_groupbox_4)
        self.keys_label_6.setGeometry(QtCore.QRect(10, 200, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_6.setFont(font)
        self.keys_label_6.setStyleSheet("      background-color: #33CCCC;\n"
"    border: 0px solid gray;\n"
"    border-radius: 0px;    ")
        self.keys_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_6.setObjectName("keys_label_6")
        self.comboBox_del = QtWidgets.QComboBox(self.filter_groupbox_4)
        self.comboBox_del.setGeometry(QtCore.QRect(20, 250, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_del.setFont(font)
        self.comboBox_del.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_del.setObjectName("comboBox_del")
        self.comboBox_del.addItem("")
        self.comboBox_del.addItem("")
        self.comboBox_del.addItem("")
        self.checkBox_del_stb = QtWidgets.QCheckBox(self.filter_groupbox_4)
        self.checkBox_del_stb.setGeometry(QtCore.QRect(10, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_del_stb.setFont(font)
        self.checkBox_del_stb.setStyleSheet("background-color: #33CCCC;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.checkBox_del_stb.setChecked(True)
        self.checkBox_del_stb.setObjectName("checkBox_del_stb")
        self.gridLayout_2.addWidget(self.filter_groupbox_4, 5, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.filter_groupbox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.filter_groupbox_5.setMinimumSize(QtCore.QSize(140, 297))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filter_groupbox_5.setFont(font)
        self.filter_groupbox_5.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0px;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: 0px;\n"
"  padding-left: 8px;\n"
"}")
        self.filter_groupbox_5.setObjectName("filter_groupbox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.filter_groupbox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.logo_2 = QtWidgets.QLabel(self.filter_groupbox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_2.sizePolicy().hasHeightForWidth())
        self.logo_2.setSizePolicy(sizePolicy)
        self.logo_2.setMinimumSize(QtCore.QSize(120, 120))
        self.logo_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.logo_2.setStyleSheet("image: url(:/newPrefix/logo2.png);")
        self.logo_2.setText("")
        self.logo_2.setObjectName("logo_2")
        self.gridLayout_3.addWidget(self.logo_2, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.filter_groupbox_5)
        self.filter_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_groupbox.sizePolicy().hasHeightForWidth())
        self.filter_groupbox.setSizePolicy(sizePolicy)
        self.filter_groupbox.setMinimumSize(QtCore.QSize(504, 297))
        self.filter_groupbox.setSizeIncrement(QtCore.QSize(0, 0))
        self.filter_groupbox.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.filter_groupbox.setFont(font)
        self.filter_groupbox.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0px;\n"
"    background-color: #FFFF95\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: 0px;\n"
"  padding-left: 8px;\n"
"}")
        self.filter_groupbox.setObjectName("filter_groupbox")
        self.comboBox_keys = QtWidgets.QComboBox(self.filter_groupbox)
        self.comboBox_keys.setGeometry(QtCore.QRect(30, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_keys.setFont(font)
        self.comboBox_keys.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_keys.setObjectName("comboBox_keys")
        self.comboBox_keys.addItem("")
        self.checkBox_filter = QtWidgets.QCheckBox(self.filter_groupbox)
        self.checkBox_filter.setGeometry(QtCore.QRect(20, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_filter.setFont(font)
        self.checkBox_filter.setStyleSheet("background-color: #FFFF95;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.checkBox_filter.setObjectName("checkBox_filter")
        self.list_selected_unique_keys = QtWidgets.QListWidget(self.filter_groupbox)
        self.list_selected_unique_keys.setGeometry(QtCore.QRect(280, 90, 211, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_selected_unique_keys.setFont(font)
        self.list_selected_unique_keys.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_selected_unique_keys.setObjectName("list_selected_unique_keys")
        self.pushButton_delete_unique_keys = QtWidgets.QPushButton(self.filter_groupbox)
        self.pushButton_delete_unique_keys.setGeometry(QtCore.QRect(240, 140, 31, 31))
        self.pushButton_delete_unique_keys.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_delete_unique_keys.setObjectName("pushButton_delete_unique_keys")
        self.pushButton_add_unique_keys = QtWidgets.QPushButton(self.filter_groupbox)
        self.pushButton_add_unique_keys.setGeometry(QtCore.QRect(240, 190, 31, 31))
        self.pushButton_add_unique_keys.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add_unique_keys.setObjectName("pushButton_add_unique_keys")
        self.list_unique_keys = QtWidgets.QListWidget(self.filter_groupbox)
        self.list_unique_keys.setGeometry(QtCore.QRect(20, 90, 211, 171))
        self.list_unique_keys.setMinimumSize(QtCore.QSize(4, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_unique_keys.setFont(font)
        self.list_unique_keys.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}")
        self.list_unique_keys.setObjectName("list_unique_keys")
        self.keys_label_4 = QtWidgets.QLabel(self.filter_groupbox)
        self.keys_label_4.setGeometry(QtCore.QRect(30, 40, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_4.setFont(font)
        self.keys_label_4.setStyleSheet("background-color: #FFFF95;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_4.setObjectName("keys_label_4")
        self.lineEdit_filter = QtWidgets.QLineEdit(self.filter_groupbox)
        self.lineEdit_filter.setGeometry(QtCore.QRect(290, 40, 191, 21))
        self.lineEdit_filter.setObjectName("lineEdit_filter")
        self.keys_label_15 = QtWidgets.QLabel(self.filter_groupbox)
        self.keys_label_15.setGeometry(QtCore.QRect(290, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_15.setFont(font)
        self.keys_label_15.setStyleSheet("background-color: #FFFF95;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_15.setObjectName("keys_label_15")
        self.pushButton_filter_download_keys = QtWidgets.QPushButton(self.filter_groupbox)
        self.pushButton_filter_download_keys.setGeometry(QtCore.QRect(290, 70, 108, 21))
        self.pushButton_filter_download_keys.setMinimumSize(QtCore.QSize(101, 0))
        self.pushButton_filter_download_keys.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_filter_download_keys.setObjectName("pushButton_filter_download_keys")
        self.pushButton_filter_clear_keys = QtWidgets.QPushButton(self.filter_groupbox)
        self.pushButton_filter_clear_keys.setGeometry(QtCore.QRect(390, 270, 81, 20))
        self.pushButton_filter_clear_keys.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#CC0000;\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_filter_clear_keys.setObjectName("pushButton_filter_clear_keys")
        self.horizontalLayout_3.addWidget(self.filter_groupbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 4, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setMinimumSize(QtCore.QSize(0, 0))
        self.logo.setMaximumSize(QtCore.QSize(16777215, 250))
        self.logo.setStyleSheet("image: url(:/newPrefix/logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.horizontalLayout_5.addWidget(self.logo)
        self.mbu_fk = QtWidgets.QLabel(self.centralwidget)
        self.mbu_fk.setMinimumSize(QtCore.QSize(0, 0))
        self.mbu_fk.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.mbu_fk.setFont(font)
        self.mbu_fk.setObjectName("mbu_fk")
        self.horizontalLayout_5.addWidget(self.mbu_fk)
        self.mbu_fk_2 = QtWidgets.QLabel(self.centralwidget)
        self.mbu_fk_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.mbu_fk_2.setFont(font)
        self.mbu_fk_2.setObjectName("mbu_fk_2")
        self.horizontalLayout_5.addWidget(self.mbu_fk_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setMinimumSize(QtCore.QSize(70, 0))
        self.version.setMaximumSize(QtCore.QSize(16777215, 35))
        self.version.setObjectName("version")
        self.horizontalLayout_2.addWidget(self.version)
        self.help_button = QtWidgets.QPushButton(self.centralwidget)
        self.help_button.setMinimumSize(QtCore.QSize(80, 0))
        self.help_button.setMaximumSize(QtCore.QSize(80, 35))
        self.help_button.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.help_button.setObjectName("help_button")
        self.horizontalLayout_2.addWidget(self.help_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 3, 1, 1)
        self.groupBox_primary_file = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_primary_file.setEnabled(True)
        self.groupBox_primary_file.setMinimumSize(QtCore.QSize(765, 517))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_primary_file.setFont(font)
        self.groupBox_primary_file.setStyleSheet("QGroupBox {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0px;\n"
"    background-color: #FFFFDE;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  background-color: transparent;\n"
"  padding-top: 0px;\n"
"  padding-left: 8px;\n"
"}")
        self.groupBox_primary_file.setObjectName("groupBox_primary_file")
        self.button_open_file = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.button_open_file.setGeometry(QtCore.QRect(10, 20, 121, 23))
        self.button_open_file.setMinimumSize(QtCore.QSize(120, 0))
        self.button_open_file.setAutoFillBackground(False)
        self.button_open_file.setStyleSheet("\n"
"QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }\n"
"")
        self.button_open_file.setCheckable(False)
        self.button_open_file.setChecked(False)
        self.button_open_file.setAutoRepeatDelay(300)
        self.button_open_file.setObjectName("button_open_file")
        self.keys_label = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label.setGeometry(QtCore.QRect(300, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label.setFont(font)
        self.keys_label.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #FFFFDE;")
        self.keys_label.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label.setObjectName("keys_label")
        self.keys_label_2 = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label_2.setGeometry(QtCore.QRect(550, 140, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_2.setFont(font)
        self.keys_label_2.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #FFFFDE;")
        self.keys_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_2.setObjectName("keys_label_2")
        self.list_keys = QtWidgets.QListWidget(self.groupBox_primary_file)
        self.list_keys.setEnabled(True)
        self.list_keys.setGeometry(QtCore.QRect(280, 160, 211, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_keys.setFont(font)
        self.list_keys.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"\n"
"}\n"
"")
        self.list_keys.setObjectName("list_keys")
        self.pushButton_delete = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_delete.setGeometry(QtCore.QRect(500, 180, 31, 31))
        self.pushButton_delete.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_add.setGeometry(QtCore.QRect(500, 230, 31, 31))
        self.pushButton_add.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add.setObjectName("pushButton_add")
        self.list_selected_keys = QtWidgets.QListWidget(self.groupBox_primary_file)
        self.list_selected_keys.setGeometry(QtCore.QRect(540, 160, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_selected_keys.setFont(font)
        self.list_selected_keys.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_selected_keys.setObjectName("list_selected_keys")
        self.pushButton_up = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_up.setGeometry(QtCore.QRect(600, 290, 31, 31))
        self.pushButton_up.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_down = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_down.setGeometry(QtCore.QRect(650, 290, 31, 31))
        self.pushButton_down.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_down.setObjectName("pushButton_down")
        self.comboBox_list_1 = QtWidgets.QComboBox(self.groupBox_primary_file)
        self.comboBox_list_1.setGeometry(QtCore.QRect(340, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_list_1.setFont(font)
        self.comboBox_list_1.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_list_1.setObjectName("comboBox_list_1")
        self.comboBox_list_1.addItem("")
        self.keys_label_8 = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label_8.setGeometry(QtCore.QRect(330, 10, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_8.setFont(font)
        self.keys_label_8.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #FFFFDE;")
        self.keys_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_8.setObjectName("keys_label_8")
        self.spinBox_list = QtWidgets.QSpinBox(self.groupBox_primary_file)
        self.spinBox_list.setEnabled(True)
        self.spinBox_list.setGeometry(QtCore.QRect(340, 100, 151, 31))
        font = QtGui.QFont()
        font.setKerning(True)
        self.spinBox_list.setFont(font)
        self.spinBox_list.setMinimum(1)
        self.spinBox_list.setMaximum(9999)
        self.spinBox_list.setProperty("value", 1)
        self.spinBox_list.setObjectName("spinBox_list")
        self.keys_label_10 = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label_10.setGeometry(QtCore.QRect(340, 80, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_10.setFont(font)
        self.keys_label_10.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #FFFFDE;")
        self.keys_label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_10.setObjectName("keys_label_10")
        self.keys_label_12 = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label_12.setGeometry(QtCore.QRect(20, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_12.setFont(font)
        self.keys_label_12.setStyleSheet("background-color: #FFFFDE;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_12.setObjectName("keys_label_12")
        self.comboBox_head = QtWidgets.QComboBox(self.groupBox_primary_file)
        self.comboBox_head.setGeometry(QtCore.QRect(20, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_head.setFont(font)
        self.comboBox_head.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_head.setObjectName("comboBox_head")
        self.comboBox_head.addItem("")
        self.comboBox_head.addItem("")
        self.button_auto_select_str = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.button_auto_select_str.setGeometry(QtCore.QRect(290, 100, 41, 31))
        self.button_auto_select_str.setAutoFillBackground(False)
        self.button_auto_select_str.setStyleSheet("\n"
"QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }\n"
"")
        self.button_auto_select_str.setText("")
        self.button_auto_select_str.setCheckable(False)
        self.button_auto_select_str.setChecked(False)
        self.button_auto_select_str.setAutoRepeatDelay(300)
        self.button_auto_select_str.setObjectName("button_auto_select_str")
        self.keys_label_19 = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label_19.setGeometry(QtCore.QRect(270, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_19.setFont(font)
        self.keys_label_19.setStyleSheet("background-color: #FFFFDE;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_19.setObjectName("keys_label_19")
        self.keys_label_calculations = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label_calculations.setGeometry(QtCore.QRect(540, 330, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_calculations.setFont(font)
        self.keys_label_calculations.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #FFFFDE;")
        self.keys_label_calculations.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_calculations.setObjectName("keys_label_calculations")
        self.list_selected_keys_4 = QtWidgets.QListWidget(self.groupBox_primary_file)
        self.list_selected_keys_4.setGeometry(QtCore.QRect(540, 350, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_selected_keys_4.setFont(font)
        self.list_selected_keys_4.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_selected_keys_4.setObjectName("list_selected_keys_4")
        self.pushButton_delete_4 = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_delete_4.setGeometry(QtCore.QRect(500, 370, 31, 31))
        self.pushButton_delete_4.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_delete_4.setObjectName("pushButton_delete_4")
        self.pushButton_add_4 = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_add_4.setGeometry(QtCore.QRect(500, 420, 31, 31))
        self.pushButton_add_4.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add_4.setObjectName("pushButton_add_4")
        self.pushButton_up_4 = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_up_4.setGeometry(QtCore.QRect(600, 480, 31, 31))
        self.pushButton_up_4.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_up_4.setObjectName("pushButton_up_4")
        self.pushButton_down_4 = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_down_4.setGeometry(QtCore.QRect(650, 480, 31, 31))
        self.pushButton_down_4.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 123, 255);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_down_4.setObjectName("pushButton_down_4")
        self.list_table_selected = QtWidgets.QListWidget(self.groupBox_primary_file)
        self.list_table_selected.setGeometry(QtCore.QRect(20, 160, 211, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_table_selected.setFont(font)
        self.list_table_selected.setStyleSheet("QListWidget {\n"
"  border: 1px solid gray;\n"
"  border-radius: 9px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"")
        self.list_table_selected.setObjectName("list_table_selected")
        self.keys_label_16 = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label_16.setGeometry(QtCore.QRect(20, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_16.setFont(font)
        self.keys_label_16.setStyleSheet("border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;\n"
"background-color: #FFFFDE;")
        self.keys_label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_16.setObjectName("keys_label_16")
        self.comboBox_config = QtWidgets.QComboBox(self.groupBox_primary_file)
        self.comboBox_config.setGeometry(QtCore.QRect(540, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_config.setFont(font)
        self.comboBox_config.setStyleSheet("QComboBox {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
"color: #333;\n"
"/*padding: 8px;*/\n"
"}\n"
"  \n"
"QComboBox::drop-down {\n"
"border: 1px solid #D3D3D3;\n"
"border-radius: 2px;\n"
" }\n"
" \n"
"QComboBox::down-arrow {\n"
"padding: 0px 1px 0px 1px;\n"
"image: url(:/doors/icons/triangle.png);\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,stop: 0 #EEEEEE, stop: 1 #FFFFFF);\n"
" }\n"
" \n"
" \n"
"QComboBox::down-arrow:on {\n"
" \n"
" }\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_config.setObjectName("comboBox_config")
        self.comboBox_config.addItem("")
        self.keys_label_18 = QtWidgets.QLabel(self.groupBox_primary_file)
        self.keys_label_18.setGeometry(QtCore.QRect(530, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.keys_label_18.setFont(font)
        self.keys_label_18.setStyleSheet("background-color: #FFFFDE;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.keys_label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_label_18.setObjectName("keys_label_18")
        self.pushButton_add_config = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_add_config.setGeometry(QtCore.QRect(540, 70, 121, 21))
        self.pushButton_add_config.setMinimumSize(QtCore.QSize(101, 0))
        self.pushButton_add_config.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0,150, 20);\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_add_config.setObjectName("pushButton_add_config")
        self.pushButton_filter_del_config = QtWidgets.QPushButton(self.groupBox_primary_file)
        self.pushButton_filter_del_config.setGeometry(QtCore.QRect(670, 70, 81, 21))
        self.pushButton_filter_del_config.setStyleSheet("QPushButton {\n"
"    font: 75 13pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#CC0000;\n"
"    border-color: #007bff;\n"
"    border: 10px;\n"
"    border-radius: 5px;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #4975a5;     \n"
" }\n"
"QPushButton:hover {\n"
"    background-color: #4975a5;\n"
" }")
        self.pushButton_filter_del_config.setObjectName("pushButton_filter_del_config")
        self.msg_label = QtWidgets.QLabel(self.groupBox_primary_file)
        self.msg_label.setGeometry(QtCore.QRect(540, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.msg_label.setFont(font)
        self.msg_label.setStyleSheet("background-color: #FFFFDE;\n"
"border: 0px solid gray;\n"
"border-radius: 0px;\n"
"margin-top: 0em;")
        self.msg_label.setText("")
        self.msg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.msg_label.setObjectName("msg_label")
        self.checkBox_group_str = QtWidgets.QCheckBox(self.groupBox_primary_file)
        self.checkBox_group_str.setGeometry(QtCore.QRect(10, 50, 221, 20))
        self.checkBox_group_str.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_group_str.setFont(font)
        self.checkBox_group_str.setStyleSheet("QCheckBox {\n"
"      background-color: #FFFFDE;\n"
"    border: 0px solid gray;\n"
"    border-radius: 0px;    \n"
"}\n"
"\n"
"")
        self.checkBox_group_str.setChecked(False)
        self.checkBox_group_str.setObjectName("checkBox_group_str")
        self.gridLayout_2.addWidget(self.groupBox_primary_file, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1589, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Обработчик"))
        self.filter_groupbox_3.setTitle(_translate("MainWindow", "Фильтр"))
        self.comboBox_keys_2.setItemText(0, _translate("MainWindow", "Нет"))
        self.checkBox_filter_2.setText(_translate("MainWindow", "Использовать фильтр"))
        self.pushButton_delete_unique_keys_2.setText(_translate("MainWindow", "<"))
        self.pushButton_add_unique_keys_2.setText(_translate("MainWindow", ">"))
        self.keys_label_14.setText(_translate("MainWindow", "Выберите столбец"))
        self.pushButton_filter_clear_keys_2.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_filter_download_keys_2.setText(_translate("MainWindow", "Подгрузить"))
        self.keys_label_21.setText(_translate("MainWindow", "Формула"))
        self.groupBox_secondary_file.setTitle(_translate("MainWindow", "Сопоставляемый файл"))
        self.button_open_file_2.setText(_translate("MainWindow", "открыть файл"))
        self.keys_label_3.setText(_translate("MainWindow", "Список столбцов"))
        self.keys_label_5.setText(_translate("MainWindow", "Список выбранных столбцов"))
        self.pushButton_delete_2.setText(_translate("MainWindow", ">"))
        self.pushButton_add_2.setText(_translate("MainWindow", "<"))
        self.pushButton_down_2.setText(_translate("MainWindow", "↓"))
        self.pushButton_up_2.setText(_translate("MainWindow", "↑"))
        self.comboBox_list_2.setItemText(0, _translate("MainWindow", "Нет"))
        self.pushButton_delete_3.setText(_translate("MainWindow", "<"))
        self.pushButton_add_3.setText(_translate("MainWindow", ">"))
        self.keys_label_7.setText(_translate("MainWindow", "Подгружаемые столбцы"))
        self.pushButton_up_3.setText(_translate("MainWindow", "↑"))
        self.pushButton_down_3.setText(_translate("MainWindow", "↓"))
        self.keys_label_9.setText(_translate("MainWindow", "Выбранный лист"))
        self.keys_label_11.setText(_translate("MainWindow", "Первая строка таблицы"))
        self.keys_label_13.setText(_translate("MainWindow", "Наличие шапки"))
        self.comboBox_head_2.setItemText(0, _translate("MainWindow", "Да"))
        self.comboBox_head_2.setItemText(1, _translate("MainWindow", "Нет"))
        self.keys_label_20.setText(_translate("MainWindow", "Подбор"))
        self.keys_label_calculations_2.setText(_translate("MainWindow", "Столбцы для вычислений"))
        self.pushButton_add_5.setText(_translate("MainWindow", "<"))
        self.pushButton_delete_5.setText(_translate("MainWindow", ">"))
        self.pushButton_up_5.setText(_translate("MainWindow", "↑"))
        self.pushButton_down_5.setText(_translate("MainWindow", "↓"))
        self.keys_label_17.setText(_translate("MainWindow", "Выбранные файлы"))
        self.keys_label_22.setText(_translate("MainWindow", "Конфигурация"))
        self.comboBox_config_2.setItemText(0, _translate("MainWindow", "Нет"))
        self.pushButton_add_config_2.setText(_translate("MainWindow", "Создать новую"))
        self.pushButton_filter_del_config_2.setText(_translate("MainWindow", "Удалить"))
        self.checkBox_group_str_2.setText(_translate("MainWindow", "Есть группированные строки\n"
"(только для .xlsx)"))
        self.progressBarMsg.setText(_translate("MainWindow", "Начало работы"))
        self.comboBox_function.setItemText(0, _translate("MainWindow", "Стандартная обработка"))
        self.comboBox_function.setItemText(1, _translate("MainWindow", "Только уникальные (по заполнености)"))
        self.comboBox_function.setItemText(2, _translate("MainWindow", "Склеить данные"))
        self.comboBox_function.setItemText(3, _translate("MainWindow", "Сопоставить две таблицы"))
        self.comboBox_function.setItemText(4, _translate("MainWindow", "Вычисление разностей"))
        self.result_button.setText(_translate("MainWindow", "Результат"))
        self.filter_groupbox_4.setTitle(_translate("MainWindow", "Настройки"))
        self.checkBox_open.setText(_translate("MainWindow", "\n"
"Открыть файл по завершению\n"
"обработки "))
        self.checkBox_color.setText(_translate("MainWindow", "\n"
"Аналитическая раскраска\n"
"столбцов"))
        self.checkBox_join_keys.setText(_translate("MainWindow", "Склеить выбранные ключи"))
        self.keys_label_6.setText(_translate("MainWindow", "Действия над строками\n"
"с пометкой \"Удалить\""))
        self.comboBox_del.setItemText(0, _translate("MainWindow", "Оставить как есть"))
        self.comboBox_del.setItemText(1, _translate("MainWindow", "Пометить красным"))
        self.comboBox_del.setItemText(2, _translate("MainWindow", "Удалить"))
        self.checkBox_del_stb.setText(_translate("MainWindow", "Убрать не участвующие в\n"
"анализе столбцы"))
        self.filter_groupbox_5.setTitle(_translate("MainWindow", "Авторы"))
        self.filter_groupbox.setTitle(_translate("MainWindow", "Фильтр"))
        self.comboBox_keys.setItemText(0, _translate("MainWindow", "Нет"))
        self.checkBox_filter.setText(_translate("MainWindow", "Использовать фильтр"))
        self.pushButton_delete_unique_keys.setText(_translate("MainWindow", "<"))
        self.pushButton_add_unique_keys.setText(_translate("MainWindow", ">"))
        self.keys_label_4.setText(_translate("MainWindow", "Выберите столбец"))
        self.keys_label_15.setText(_translate("MainWindow", "Формула"))
        self.pushButton_filter_download_keys.setText(_translate("MainWindow", "Подгрузить"))
        self.pushButton_filter_clear_keys.setText(_translate("MainWindow", "Очистить"))
        self.mbu_fk.setText(_translate("MainWindow", "Межрегиональное Бухгалтерское"))
        self.mbu_fk_2.setText(_translate("MainWindow", " УФК"))
        self.version.setText(_translate("MainWindow", "ver. 0.9"))
        self.help_button.setText(_translate("MainWindow", "Помощь"))
        self.groupBox_primary_file.setTitle(_translate("MainWindow", "Основной файл"))
        self.button_open_file.setText(_translate("MainWindow", "открыть файл"))
        self.keys_label.setText(_translate("MainWindow", "Список столбцов"))
        self.keys_label_2.setText(_translate("MainWindow", "Список выбранных столбцов"))
        self.pushButton_delete.setText(_translate("MainWindow", "<"))
        self.pushButton_add.setText(_translate("MainWindow", ">"))
        self.pushButton_up.setText(_translate("MainWindow", "↑"))
        self.pushButton_down.setText(_translate("MainWindow", "↓"))
        self.comboBox_list_1.setItemText(0, _translate("MainWindow", "Нет"))
        self.keys_label_8.setText(_translate("MainWindow", "Выбранный лист"))
        self.keys_label_10.setText(_translate("MainWindow", "Первая строка таблицы"))
        self.keys_label_12.setText(_translate("MainWindow", "Наличие шапки"))
        self.comboBox_head.setItemText(0, _translate("MainWindow", "Да"))
        self.comboBox_head.setItemText(1, _translate("MainWindow", "Нет"))
        self.keys_label_19.setText(_translate("MainWindow", "Подбор"))
        self.keys_label_calculations.setText(_translate("MainWindow", "Столбцы для вычислений"))
        self.pushButton_delete_4.setText(_translate("MainWindow", "<"))
        self.pushButton_add_4.setText(_translate("MainWindow", ">"))
        self.pushButton_up_4.setText(_translate("MainWindow", "↑"))
        self.pushButton_down_4.setText(_translate("MainWindow", "↓"))
        self.keys_label_16.setText(_translate("MainWindow", "Выбранные файлы"))
        self.comboBox_config.setItemText(0, _translate("MainWindow", "Нет"))
        self.keys_label_18.setText(_translate("MainWindow", "Конфигурация"))
        self.pushButton_add_config.setText(_translate("MainWindow", "Создать новую"))
        self.pushButton_filter_del_config.setText(_translate("MainWindow", "Удалить"))
        self.checkBox_group_str.setText(_translate("MainWindow", "Есть группированные строки\n"
"(только для .xlsx)"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
